- name: Set timezone and configure timesyncd
hosts: "*"
become: yes
tasks:
  - name: set timezone
    shell: timedatectl set-timezone America/New_York

  - name: Make sure timesyncd is stop
    systemd:
      name: systemd-timesynd.service
      state: stopped

  - name: Copy over the timesyncd config
    template: src=../templates/timesyncd.conf dest=/etc/systemd/timesyncd.conf

  - name: Make sure timesyncd is started
    systemd:
      name: system-timesyncd.service
      state: started